// figure.prop_11.f1.asy -- If a body revolves in an ellipse, find the law of the centripetal force tending to the focus of the ellipse.
// Self-contained convention. Compile: asy -u "highlight=k" figure.prop_11.f1.asy
// highlight=-1 => OFF (all black). highlight=k => step k colors + step k heart Stabilo.

import geometry;
import graph;
settings.outformat = "png";
unitsize(1cm);

int highlight = -1;
usersetting();

// ---- palette (LOCAL; pure black when uncolored) ----
pen BLACK = rgb(0,0,0) + linewidth(1.0pt);
pen ellblue = rgb(30/255, 111/255, 224/255) + linewidth(1.6pt);
pen fociorange = rgb(232/255, 119/255, 10/255) + linewidth(1.6pt);
pen radgreen = rgb(0/255, 163/255, 90/255) + linewidth(1.6pt);
pen equalpurple = rgb(142/255, 36/255, 170/255) + linewidth(1.6pt);
pen parteal = rgb(0/255, 137/255, 123/255) + linewidth(1.6pt);
pen latusred = rgb(216/255, 27/255, 96/255) + linewidth(1.6pt);
pen resultblue = rgb(30/255, 111/255, 224/255) + linewidth(1.6pt);

// ---- bright Stabilo markers (current-step heart only; laid UNDER the ink) ----
pen STABILO_1_1 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_1_2 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_1_3 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_2_1 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_3_1 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_3_2 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_4_1 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;
pen STABILO_5_1 = rgb(255/255, 224/255, 0/255) + opacity(0.45) + linewidth(9pt) + squarecap;

// ---- ZONE 2: construction ----
pair C = (0.0,0.0);
pair A = (-5.0,0.0);
pair Ap = (5.0,0.0);
pair B = (0.0,3.0);
pair Bp = (0.0,-3.0);
pair _u_S = (-4.0,0.0);
pair H = (4.0,0.0);
pair P = (2.5,2.34);
ellipse ell = ellipse(C, A, B);
path MAJ = A--Ap;
path MIN = B--Bp;
pair S2 = (-4.0,0.0);
pair H2 = (4.0,0.0);
path SP = _u_S--P;
pair _u_E = (-2.5,-2.34);
path HP = H--P;
path PE = P--_u_E;
path EC = _u_E--C;
pair G = (-2.5,-2.34);
pair D = (-2.8,1.68);
pair K = (2.8,-1.68);
pair Q = (3.4,1.71);
pair v = (2.87,1.98);
pair x = (3.03,1.53);
pair R = (3.87,1.89);
path PG = P--G;
path DK = D--K;
pair T = (1.7,0.9);
path QT = Q--T;
path Qv = Q--v;
path PAR = P--v--Q--x--cycle;
path PR = P--R;
pair Ls = (-4.0,1.8);
pair Le = (-4.0,-1.8);
path CB = C--B;
path CD = C--D;
path LAT = Ls--Le;
path fld = circle(_u_S, 6.79);

// ---- ZONE 4: render (highlight-driven) ----
void drawAll(int highlight) {
  bool on1 = (highlight==1);
  bool on2 = (highlight==2);
  bool on3 = (highlight==3);
  bool on4 = (highlight==4);
  bool on5 = (highlight==5);

  // STABILO underlay (current step's heart only)
  if (on1) dot(S2, STABILO_1_1);
  if (on1) dot(H2, STABILO_1_2);
  if (on1) draw(SP, STABILO_1_3);
  if (on2) draw(PE, STABILO_2_1);
  if (on3) draw(PG, STABILO_3_1);
  if (on3) draw(DK, STABILO_3_2);
  if (on4) draw(LAT, STABILO_4_1);
  if (on5) draw(fld, STABILO_5_1);

  // ink pass
  dot(C, on5 ? BLACK : BLACK);
  dot(A, on5 ? BLACK : BLACK);
  dot(B, on5 ? BLACK : BLACK);
  dot(_u_S, on5 ? BLACK : BLACK);
  dot(P, on5 ? BLACK : BLACK);
  draw(ell, on5 ? ellblue : BLACK);
  draw(SP, on5 ? radgreen : BLACK);
  draw(fld, on5 ? resultblue : BLACK);
  dot(C, on4 ? BLACK : BLACK);
  dot(A, on4 ? BLACK : BLACK);
  dot(B, on4 ? BLACK : BLACK);
  dot(_u_S, on4 ? BLACK : BLACK);
  dot(P, on4 ? BLACK : BLACK);
  dot(G, on4 ? BLACK : BLACK);
  dot(D, on4 ? BLACK : BLACK);
  dot(K, on4 ? BLACK : BLACK);
  dot(Ls, on4 ? BLACK : BLACK);
  dot(Le, on4 ? BLACK : BLACK);
  draw(ell, on4 ? ellblue : BLACK);
  draw(PG, on4 ? parteal : BLACK);
  draw(DK, on4 ? parteal : BLACK);
  draw(CB, on4 ? parteal : BLACK);
  draw(CD, on4 ? parteal : BLACK);
  draw(LAT, on4 ? latusred : BLACK);
  dot(C, on3 ? BLACK : BLACK);
  dot(A, on3 ? BLACK : BLACK);
  dot(B, on3 ? BLACK : BLACK);
  dot(_u_S, on3 ? BLACK : BLACK);
  dot(P, on3 ? BLACK : BLACK);
  dot(G, on3 ? BLACK : BLACK);
  dot(D, on3 ? BLACK : BLACK);
  dot(K, on3 ? BLACK : BLACK);
  dot(Q, on3 ? BLACK : BLACK);
  dot(v, on3 ? BLACK : BLACK);
  dot(x, on3 ? BLACK : BLACK);
  dot(R, on3 ? BLACK : BLACK);
  draw(ell, on3 ? ellblue : BLACK);
  draw(PG, on3 ? parteal : BLACK);
  draw(DK, on3 ? parteal : BLACK);
  draw(SP, on3 ? radgreen : BLACK);
  dot(T, on3 ? BLACK : BLACK);
  draw(QT, on3 ? BLACK : BLACK);
  draw(Qv, on3 ? parteal : BLACK);
  draw(PAR, on3 ? parteal : BLACK);
  draw(PR, on3 ? parteal : BLACK);
  dot(C, on2 ? BLACK : BLACK);
  dot(A, on2 ? BLACK : BLACK);
  dot(Ap, on2 ? BLACK : BLACK);
  dot(B, on2 ? BLACK : BLACK);
  dot(_u_S, on2 ? BLACK : BLACK);
  dot(H, on2 ? BLACK : BLACK);
  dot(P, on2 ? BLACK : BLACK);
  dot(_u_E, on2 ? BLACK : BLACK);
  draw(ell, on2 ? ellblue : BLACK);
  draw(MAJ, on2 ? BLACK : BLACK);
  draw(SP, on2 ? radgreen : BLACK);
  draw(HP, on2 ? radgreen : BLACK);
  draw(PE, on2 ? equalpurple : BLACK);
  draw(EC, on2 ? equalpurple : BLACK);
  dot(C, on1 ? BLACK : BLACK);
  dot(A, on1 ? BLACK : BLACK);
  dot(Ap, on1 ? BLACK : BLACK);
  dot(B, on1 ? BLACK : BLACK);
  dot(Bp, on1 ? BLACK : BLACK);
  dot(_u_S, on1 ? BLACK : BLACK);
  dot(H, on1 ? BLACK : BLACK);
  dot(P, on1 ? BLACK : BLACK);
  draw(ell, on1 ? ellblue : BLACK);
  draw(MAJ, on1 ? BLACK : BLACK);
  draw(MIN, on1 ? BLACK : BLACK);
  draw(SP, on1 ? radgreen : BLACK);
  label("$C$", C, S);
  label("$A$", A, W);
  label("$A'$", Ap, E);
  label("$B$", B, N);
  label("$B'$", Bp, S);
  label("$S$", _u_S, SW);
  label("$H$", H, SE);
  label("$P$", P, NE);
  label("$C$", C, S);
  label("$A$", A, W);
  label("$A'$", Ap, E);
  label("$S$", _u_S, SW);
  label("$H$", H, SE);
  label("$P$", P, NE);
  label("$E$", _u_E, SW);
  label("$C$", C, SW);
  label("$S$", _u_S, SW);
  label("$P$", P, NE);
  label("$G$", G, SW);
  label("$D$", D, NW);
  label("$K$", K, SE);
  label("$Q$", Q, E);
  label("$v$", v, N);
  label("$x$", x, SE);
  label("$R$", R, E);
  label("$T$", T, S);
  label("$C$", C, SW);
  label("$B$", B, N);
  label("$S$", _u_S, SW);
  label("$P$", P, NE);
  label("$D$", D, NW);
  label("$L_1$", Ls, NW);
  label("$L_2$", Le, SW);
  label("$C$", C, S);
  label("$S$", _u_S, SW);
  label("$P$", P, NE);
}
drawAll(highlight);
