"""
notation.py — staff-drawing lookups. [MEAT as of M2 — fattened by Parent 3]

Scripture: New Testament Addendum A. The Player knows NO music theory:
it renders notation purely by looking up player/data/notation_table.json
(MIDI 36-96: display name, staff step per clef, sharp flag), which is
GENERATED by compiler/notation_gen.py — one source of truth. Until the
Compiler parent writes the real generator, DeepSeek supplies a temporary
stand-in file in EXACTLY the frozen on-disk format below.

THE FROZEN ON-DISK FORMAT (the contract; generator + stand-in match it):

    {
      "format": "loom-notation-table",
      "format_version": "1.0",
      "midi_min": 36,
      "midi_max": 96,
      "entries": [
        {"midi": 60, "name": "C4", "treble_step": -6, "bass_step": 6,
         "sharp": false}
      ]
    }

    - entries must cover every integer midi_min..midi_max exactly once.
    - name: sharps convention with 's' (C4, Cs4, ...); MIDI 60 = C4.
    - *_step: diatonic staff steps, 0 = the clef's MIDDLE line
      (treble: B4; bass: D3), +1 = one letter step UP = half a
      line-gap on screen. Anchors: treble E4 (bottom line) = -4,
      F5 (top line) = +4, C4 = -6; bass A3 (top line) = +4,
      G2 (bottom line) = -4, C4 = +6.
    - sharp: true = draw a sharp glyph left of the notehead; a sharp
      note carries the SAME step as its natural letter (Cs4 = C4's).

Imports: standard library ONLY (listed in tests/test_purity.py).
"""

from __future__ import annotations

import json
from dataclasses import dataclass


@dataclass(frozen=True)
class NotationEntry:
    midi: int
    name: str            # e.g. "C4", "Fs5" (display form decided by the table)
    treble_step: int     # vertical staff step in treble clef (0 = middle line)
    bass_step: int       # vertical staff step in bass clef
    sharp: bool          # draw a sharp sign before the notehead


class NotationTable:
    """Frozen interface: load once, look up per notehead drawn."""

    def __init__(self, entries: dict[int, NotationEntry],
                 midi_min: int, midi_max: int) -> None:
        self._entries = entries
        self._midi_by_name = {e.name: e.midi for e in entries.values()}
        self.midi_min = midi_min
        self.midi_max = midi_max

    @staticmethod
    def load(path: str) -> "NotationTable":
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if data.get("format") != "loom-notation-table":
            raise ValueError(
                f"{path}: not a loom-notation-table file "
                f"(format={data.get('format')!r})")
        version = str(data.get("format_version", ""))
        if not version.startswith("1."):
            raise ValueError(
                f"{path}: unsupported format_version {version!r} "
                "(this Player reads 1.x)")
        midi_min = int(data["midi_min"])
        midi_max = int(data["midi_max"])
        entries: dict[int, NotationEntry] = {}
        for raw in data["entries"]:
            e = NotationEntry(
                midi=int(raw["midi"]),
                name=str(raw["name"]),
                treble_step=int(raw["treble_step"]),
                bass_step=int(raw["bass_step"]),
                sharp=bool(raw["sharp"]),
            )
            if e.midi in entries:
                raise ValueError(f"{path}: duplicate entry for midi {e.midi}")
            entries[e.midi] = e
        missing = [m for m in range(midi_min, midi_max + 1)
                   if m not in entries]
        if missing:
            head = ", ".join(str(m) for m in missing[:8])
            more = " ..." if len(missing) > 8 else ""
            raise ValueError(
                f"{path}: table must cover every midi from {midi_min} to "
                f"{midi_max}; missing: {head}{more}")
        return NotationTable(entries, midi_min, midi_max)

    def entry(self, midi: int) -> NotationEntry:
        try:
            return self._entries[midi]
        except KeyError:
            raise KeyError(
                f"midi {midi} is outside the notation table "
                f"({self.midi_min}..{self.midi_max}) — the spell asks for "
                "a note the table does not know") from None

    def midi_for_name(self, name: str) -> int:
        """Reverse lookup: 'C4' -> 60. ADDITIVE method, flagged to Nir in
        Parent 3 Part 1 (see 1F). Pure dict lookup — zero music theory.
        Needed so the wiring can turn the spell's keyboard.low_note /
        high_note (note NAMES per BIBLE par.8) into midi numbers."""
        try:
            return self._midi_by_name[name]
        except KeyError:
            raise KeyError(
                f"note name {name!r} not in the notation table "
                "(expected the table's own display form, e.g. 'C4', 'Fs5')"
            ) from None
