"""
notation.py — staff-drawing lookups. [BONE M2]

Scripture: New Testament Addendum A. The Player knows NO music theory:
it renders notation purely by looking up player/data/notation_table.json
(MIDI 36-96: display name, staff step per clef, sharp flag), which is
GENERATED by compiler/notation_gen.py — one source of truth.

FATTEN ME LIKE THIS (M2 parent): implement load() + entry(); nothing
else belongs here. If you feel the urge to compute "is this note a
sharp" from midi % 12 — stop; that knowledge lives in the table file.
Imports: standard library ONLY. Add this module to test_purity.py.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class NotationEntry:
    midi: int
    name: str            # e.g. "C4", "Fs5" (display form decided by the table)
    treble_step: int     # vertical staff step in treble clef (0 = middle line)
    bass_step: int       # vertical staff step in bass clef
    sharp: bool          # draw a sharp sign before the notehead


class NotationTable:
    """Frozen interface: load once, look up per notehead drawn."""

    @staticmethod
    def load(path: str) -> "NotationTable":
        raise NotImplementedError("M2: parse notation_table.json (MIDI 36-96)")

    def entry(self, midi: int) -> NotationEntry:
        raise NotImplementedError("M2: dict lookup; plain error if out of range")
